version: "3.7"

name: biiig-image-board

services:
  biiig-image-app:
      build: ./app
      ports: 
      - "5173:5173"

  biiig-image-db:
      image: mongo:latest
      ports:
        - "27017:27017"
      # volumes: 