version: "3.8"

name: biiig-image-board

services:

    biiig-image-proxy:
        build: ./nginx
        restart: always
        ports: 
        - "3043:443"
        depends_on:
            - biiig-image-app
        volumes:
        - ./nginx/conf:/etc/nginx
        - ./nginx/certs:/etc/nginx/certs
        networks:
            - biiig-image-net
        
    biiig-image-app:
        build: ./app
        restart: always
        depends_on:
            biiig-image-db:
                condition: service_started
                restart: true
        environment:
        - DB_URI=mongodb://biiig-image-db:27017
        # - BODY_SIZE_LIMIT=Infinity
        # - SESS_COOKIE_NAME=auth_session #allows user to set unique cookie name to prevent collision
        volumes: 
        - ./images:/biiib/images # modify ./app/images to point to wanted image directory
        - ./thumb:/biiib/thumb # modify ./app/thumb to point to wanted thumbnail directory

        networks:
            - biiig-image-net

    biiig-image-db:
        image: mongo:latest
        restart: always
        # environment:
            # - MONGO_INITDB_ROOT_USERNAME=root
            # - MONGO_INITDB_ROOT_PASSWORD=example
        volumes: 
            - ./mongodb:/data/db # modify to point to mongodb data directory
        networks:
            - biiig-image-net

networks:
  biiig-image-net:
    driver: bridge
